object yaml file read: objects_clovis
object yaml file write: objects_clovis
raw forces txt file name: raw_forces
f max: 0.1:3:0.1,3:10 # DEPRECATED #start:stop:step [start,stop) if step == None -> step = 1 "," separator to vary the increments
dWext: X:Y:Z,X:Y:-Z,X:Y,X:-Y:Z,X:-Y:-Z,X:-Y,X:Z,X:-Z,X,-X:Y:Z,-X:Y:-Z,-X:Y,-X:-Y:Z,-X:-Y:-Z,-X:-Y,-X:Z,-X:-Z,-X,Y:Z,Y:-Z,Y,-Y:Z,-Y:-Z,-Y,Z,-Z,mX,-mX,mY,-mY,mZ,-mZ # "," separator for analysis, ":" Multiple directions in the same analysis, "-" to indicate negative direcction
sheet suffix: 0
