object yaml file name: objects
raw forces txt file name: raw_forces
f max:  0.1:3:0.1,3:10 #start:stop:step [start,stop) if step == None -> step = 1 "," separator to vary the increments
dWext: X,-X,Y,-Y,Z,-Z,mX,-mX,mY,-mY # "," separator for analysis, ":" Multiple directions in the same analysis, "-" to indicate negative direcction
